version: "2"
run:
  modules-download-mode: readonly
  tests: true
linters:
  enable:
    - bodyclose
    - gosec
    - misspell
    - nilerr
    - revive
    - unconvert
    - unparam
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gosec:
      excludes:
        - G404
    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
          - unparam
        path: _test\.go
      - linters:
          - revive
          - unused
        path: .*_mock\.go
      - linters:
          - unused
        path: test_helpers\.go
      - linters:
          - lll
        path: _test\.go
      - linters:
          - bodyclose
          - errcheck
          - gosec
          - govet
        path: (cmd/bootstrap|plugins/fossa/client)\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
