//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeScannerFossa) DeepCopyInto(out *CodeScannerFossa) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeScannerFossa.
func (in *CodeScannerFossa) DeepCopy() *CodeScannerFossa {
	if in == nil {
		return nil
	}
	out := new(CodeScannerFossa)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CodeScannerFossa) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeScannerFossaList) DeepCopyInto(out *CodeScannerFossaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CodeScannerFossa, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeScannerFossaList.
func (in *CodeScannerFossaList) DeepCopy() *CodeScannerFossaList {
	if in == nil {
		return nil
	}
	out := new(CodeScannerFossaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CodeScannerFossaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeScannerFossaSpec) DeepCopyInto(out *CodeScannerFossaSpec) {
	*out = *in
	if in.FossaUserEmails != nil {
		in, out := &in.FossaUserEmails, &out.FossaUserEmails
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeScannerFossaSpec.
func (in *CodeScannerFossaSpec) DeepCopy() *CodeScannerFossaSpec {
	if in == nil {
		return nil
	}
	out := new(CodeScannerFossaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeScannerFossaStatus) DeepCopyInto(out *CodeScannerFossaStatus) {
	*out = *in
	if in.FossaTeam != nil {
		in, out := &in.FossaTeam, &out.FossaTeam
		*out = new(FossaTeamReference)
		(*in).DeepCopyInto(*out)
	}
	if in.UserInvitations != nil {
		in, out := &in.UserInvitations, &out.UserInvitations
		*out = make([]FossaUserInvitation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeScannerFossaStatus.
func (in *CodeScannerFossaStatus) DeepCopy() *CodeScannerFossaStatus {
	if in == nil {
		return nil
	}
	out := new(CodeScannerFossaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeScannerSnyk) DeepCopyInto(out *CodeScannerSnyk) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeScannerSnyk.
func (in *CodeScannerSnyk) DeepCopy() *CodeScannerSnyk {
	if in == nil {
		return nil
	}
	out := new(CodeScannerSnyk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CodeScannerSnyk) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeScannerSnykList) DeepCopyInto(out *CodeScannerSnykList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CodeScannerSnyk, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeScannerSnykList.
func (in *CodeScannerSnykList) DeepCopy() *CodeScannerSnykList {
	if in == nil {
		return nil
	}
	out := new(CodeScannerSnykList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CodeScannerSnykList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeScannerSnykSpec) DeepCopyInto(out *CodeScannerSnykSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeScannerSnykSpec.
func (in *CodeScannerSnykSpec) DeepCopy() *CodeScannerSnykSpec {
	if in == nil {
		return nil
	}
	out := new(CodeScannerSnykSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeScannerSnykStatus) DeepCopyInto(out *CodeScannerSnykStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeScannerSnykStatus.
func (in *CodeScannerSnykStatus) DeepCopy() *CodeScannerSnykStatus {
	if in == nil {
		return nil
	}
	out := new(CodeScannerSnykStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FossaTeamReference) DeepCopyInto(out *FossaTeamReference) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FossaTeamReference.
func (in *FossaTeamReference) DeepCopy() *FossaTeamReference {
	if in == nil {
		return nil
	}
	out := new(FossaTeamReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FossaUserInvitation) DeepCopyInto(out *FossaUserInvitation) {
	*out = *in
	if in.InvitedAt != nil {
		in, out := &in.InvitedAt, &out.InvitedAt
		*out = (*in).DeepCopy()
	}
	if in.AcceptedAt != nil {
		in, out := &in.AcceptedAt, &out.AcceptedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FossaUserInvitation.
func (in *FossaUserInvitation) DeepCopy() *FossaUserInvitation {
	if in == nil {
		return nil
	}
	out := new(FossaUserInvitation)
	in.DeepCopyInto(out)
	return out
}
